{% set name = "libabigail" %}
{% set version = "2.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://mirrors.kernel.org/sourceware/{{ name }}/{{ name }}-{{ version }}.tar.xz
  sha256: 0cc10e6471398330e001b9fe37f1e8c5108a9ab632b08ca9634d6c64bc380b78

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    # SO name changes at minor rev bumps.
    - {{ pin_subpackage('libabigail', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - make
    - pkg-config
  host:
    - elfutils
    - libdwarf-dev
    - zlib
    - liblzma-devel
    - libxml2-devel
    - xxhash
    - icu
  run:

test:
  commands:
    - test -f ${PREFIX}/lib/libabigail${SHLIB_EXT}
    - abidiff --version

about:
  home: https://sourceware.org/libabigail/
  summary: 'ABI Generic Analysis and Instrumentation Library'
  description: |
    This is an interface to the GNU Compiler Collection for the collection
    and analysis of compiler-generated binaries.
  license: Apache-2.0 WITH LLVM-exception
  license_family: Apache
  license_file: LICENSE.txt
  doc_url: https://sourceware.org/libabigail/
  dev_url: https://sourceware.org/git/libabigail.git

extra:
  recipe-maintainers:
    - calebzulawski
